<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => 'Sicher...',
    'Article' => 'Artikel',
    'Articles' => 'Artikel',
    'Auth Key' => 'Authentifizierungsschlüssel',
    'Bill' => 'Rechnung',
    'Bills' => 'Rechnungen',
    'Comment' => 'Kommentar',
    'Create' => 'Erstelle',
    'Create Article' => 'Neuer Artikel',
    'Create Bill' => 'Neue Rechnung',
    'Create Customer' => 'Neuer Kunde',
    'Create Mandator' => 'Neuer Mandant',
    'Create Position' => 'Neue Position',
    'Create User' => 'Neuer Benutzer',
    'Created At' => 'Erstellt am',
    'Customer ID' => 'Kunden ID',
    'Customers' => 'Kunden',
    'Customer' => 'Kunde',
    'Delete' => 'Löschen',
    'Description' => 'Beschreibung',
    'Email' => 'EMail',
    'Home' => 'ZuHause',
    'ID' => 'ID',
    'Mandator ID' => 'Mandanten ID',
    'Mandator' => 'Mandant',
    'Mandators' => 'Mandanten',
    'Name' => 'Name',
    'New Position' => 'Neue Position',
    'Password Hash' => 'Passwort',
    'Password Reset Token' => 'Passwort zur Wiederherstellung',
    'Positions' => 'Positionen',
    'Price' => 'Preis',
    'Quantity' => 'Menge',
    'Reset' => 'Zuzrücksetzen',
    'Search' => 'Suche',
    'Status' => 'Status',
    'This is Reibach' => 'Dies ist Reibach',
    'Unit' => 'Einheit',
    'Update' => 'Bearbeiten',
    'Update {modelClass}: ' => '',
    'Updated At' => 'Bearbeitet am',
    'User ID' => 'Benutzer ID',
    'Username' => 'Benutzername',
	'Users' => 'Bruukers',
    'User' => 'Bruuker',
];
