<?php

/**
 * 1. bestehende Sprachdatei sichern

**/
//system ('cd /var/www/html/reibach/frontend');
//system ('mv messages messages.org');
//mkdir messages

// übersetzungsstrings aus der Anwendung holen und ins frontend schreiben 
//root@reibach-dev:/var/www/html/reibach# php yii message/extract  @frontend/config/i18n.php
//generiert: /var/www/html/reibach/frontend/messages/
//de_DE
//nds_NDS

// php yii message/extract  @frontend/config/i18n.php



// die neu generierte Sprachdatei
// var/www/html/reibach/frontend/messages/de_DE/app.php
$array_leer = array(
    'Abo End' => '',
    'Abo Start' => '',
    'Abo Turn' => '',
    'Abo Type' => '',
    'Address ID' => '',
    'Agb' => '',
    'At registration the customer must provide the required
information and agree with the general terms and conditions.' => '',
    'Check your email for further instructions.' => '',
    'Country Name' => '',
    'Create Customer Address' => '',
    'Customer Addresses' => '',
    'Customer Number' => '',
    'Disclaimer' => '',
    'Fax' => '',
    'First name' => '',
    'GTC' => '',
    'Housenumber' => '',
    'Last name' => '',
    'Name' => '',
    'New password was saved.' => '',
    'Parent person identifier' => '',
    'Please contact us if you think this is a server error. Thank you.' => '',
    'Please fill out this form...' => '',
    'Privacy Policy' => '',
    'Quick Start' => '',
    'Residing Country' => '',
    'Sorry, we are unable to reset password for email provided.' => '',
    'Street' => '',
    'Thank you for contacting us. We will respond to you as soon as possible.' => '',
    'The above error occurred while the Web server was processing your request.' => '',
    'There was an error sending email.' => '',
    'This is the About page. You may modify the following file to customize its content:' => '',
    'Unique person identifier' => '',
    'login-button' => '',
    'Address' => '@@Adresse@@',
    'Address1' => '@@Anschrift1@@',
    'Address2' => '@@Anschrift2@@',
    'Article' => '@@Artikel@@',
    'Body' => '@@Nachricht@@',
    'Home' => '@@Startseite@@',
    'Password' => '@@Passwort@@',
    'Subject' => '@@Betreff@@',
    'This email address has already been taken.' => '@@Diese EMailAdresse ist bereits vergeben.@@',
    'This username has already been taken.' => '@@Dieser Benutzername ist bereits vergeben.@@',
    'User' => '@@Benutzer@@',
    'email' => '@@EMail@@',
    'fullName' => '@@Name@@',
    'lastname' => '@@Nachname@@',
    'password' => '@@Passwort@@',
    'rememberMe' => '@@Merke@@',
    'send' => '@@senden@@',
    'username' => '@@Benutzername@@',
    'About' => 'Über...',
    'Address Type' => 'Address Typ',
    'Addresses' => 'Adressen',
    'Amount' => 'Menge',
    'Are you sure you want to delete this item?' => 'Sicher...',
    'Articles' => 'Artikel',
    'Auth Key' => 'Authentifizierungsschlüssel',
    'Bill' => 'Rechnung',
    'Bill ID' => 'Rechnungs ID',
    'Bills' => 'Rechnungen',
    'Comment' => 'Kommentar',
    'Company' => 'Firma',
    'Contact' => 'Kontakt',
    'Create' => 'Erstelle',
    'Create Address' => 'Neue Adresse',
    'Create Article' => 'Neuer Artikel',
    'Create Bill' => 'Neue Rechnung',
    'Create Customer' => 'Neuer Kunde',
    'Create Mandator' => 'Neuer Mandant',
    'Create Position' => 'Neue Position',
    'Create Time' => 'Erstellt am',
    'Create User' => 'Neuer Benutzer',
    'Create User ID' => 'Erstellt von',
    'Created At' => 'Erstellt am',
    'Customer' => 'Kunde',
    'Customer ID' => 'Kunden ID',
    'Customers' => 'Kunden',
    'Delete' => 'Löschen',
    'Description' => 'Beschreibung',
    'Email' => 'EMail',
    'Full Name' => 'Name',
    'ID' => 'ID',
    'If you forgot your password you can' => 'Wenn du dein Passwort vergessen hast, ',
    'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.' => 'Wenn du geschäftliche Anfragen oder andere Fragen hast, fülle bitte das folgende Formular aus, um uns zu kontaktieren. Vielen Dank. ',
    'Imprint' => 'Impressum',
    'Lastname' => 'Nachname',
    'Login' => 'Anmelden',
    'Mandator' => 'Mandant',
    'Mandator ID' => 'Mandanten ID',
    'Mandators' => 'Mandanten',
    'New Position' => 'Neue Position',
    'Password Hash' => 'Passwort',
    'Password Reset Token' => 'Passwort zur Wiederherstellung',
    'Phone Business' => 'Telefon geschäftlich',
    'Phone Mobile' => 'Telefon Mobil',
    'Phone Privat' => 'Telefon privat',
    'Place' => 'Ort',
    'Please fill out the following fields to login:' => 'Bitte fülle die folgenden Felder aus, um dich anzumelden. :',
    'Please fill out the following fields to signup:' => 'Bitte fülle die folgenden Felder aus, um dich zu registrieren',
    'Please fill out your email. A link to reset password will be sent there.' => 'Bitte gib deine EMail ein. Ein Link zum zurücksetzen wird dahin gesendet.',
    'Pos Num' => 'Pos-Nr.',
    'Positions' => 'Positionen',
    'Prename' => 'Vorname',
    'Price' => 'Preis',
    'Print PDF' => 'PDF drucken',
    'Quantity' => 'Anzahl',
    'Remove' => 'Löschen',
    'Request password reset' => 'Passwort zurücksetzen',
    'Reset' => 'Zuzrücksetzen',
    'Reset password' => 'Passwort zurücksetzen',
    'Search' => 'Suche',
    'Select Customer' => 'Kunde auswählen',
    'Send' => 'Senden',
    'Signup' => 'Registrieren',
    'State' => 'Bundesland',
    'Status' => 'Status',
    'Submit' => 'Absenden',
    'Tax' => 'Steuer',
    'This is Reibach' => 'Dies ist Reibach',
    'Title' => 'Titel',
    'Unit' => 'Einheit',
    'Update' => 'Bearbeiten',
    'Update Mandator: ' => 'Bearbeite Mandant:',
    'Update Time' => 'Bearbeitet am',
    'Update User ID' => 'Bearbeitet von',
    'Update {modelClass}: ' => 'Bearbeite {modelClass}:',
    'Updated At' => 'Bearbeitet am',
    'User ID' => 'Benutzer ID',
    'Username' => 'Benutzername',
    'Users' => 'Benutzer',
    'Zipcode' => 'Postleitzahl',
    'amount' => 'Menge',
    'comment' => 'Kommentar',
    'name' => 'Name',
    'pos_num' => 'Pos-Nr.',
    'prename' => 'Vorname',
    'price' => 'Preis',
    'quantity' => 'Anzahl',
    'reset it' => 'setze es zurück.',
    'tax' => 'Steuer',
    'unit' => 'Einheit',
);

// die bisherige Sprachdatei
// var/www/html/reibach/frontend/messages.org/de_DE/app.php
$array_voll = array(
	'About' => 'Über...',
	'Address' => 'Adresse',
	'Address ID' => '',
	'Address Type' => 'Address Typ',
	'Address1' => 'Anschrift1',
	'Address2' => 'Anschrift2',
	'Addresses' => 'Adressen',
	'Amount' => 'Menge',
	'Are you sure you want to delete this item?' => 'Sicher...',
	'Article' => 'Artikel',
	'Articles' => 'Artikel',
	'Auth Key' => 'Authentifizierungsschlüssel',
	'Bill' => 'Rechnung',
	'Bill ID' => 'Rechnungs ID',
	'Bills' => 'Rechnungen',
	'Body' => 'Nachricht',
	'Comment' => 'Kommentar',
	'Company' => 'Firma',
	'Contact' => 'Kontakt',
	'Create' => 'Erstelle',
	'Create Address' => 'Neue Adresse',
	'Create Article' => 'Neuer Artikel',
	'Create Bill' => 'Neue Rechnung',
	'Create Customer' => 'Neuer Kunde',
	'Create Customer Address' => '',
	'Create Mandator' => 'Neuer Mandant',
	'Create Position' => 'Neue Position',
	'Create Time' => 'Erstellt am',
	'Create User' => 'Neuer Benutzer',
	'Create User ID' => 'Erstellt von',
	'Created At' => 'Erstellt am',
	'Customer' => 'Kunde',
	'Customer Addresses' => '',
	'Customer ID' => 'Kunden ID',
	'Customers' => 'Kunden',
	'Delete' => 'Löschen',
	'Description' => 'Beschreibung',
	'Email' => 'EMail',
	'Fax' => '',
	'Full Name' => 'Name',
	'Home' => 'Startseite',
	'ID' => 'ID',
	'If you forgot your password you can' => 'Wenn du dein Passwort vergessen hast, ',
	'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.' => 'Wenn du geschäftliche Anfragen oder andere Fragen hast, fülle bitte das folgende Formular aus, um uns zu kontaktieren. Vielen Dank. ',
	'Imprint' => 'Impressum',
	'Lastname' => 'Nachname',
	'Login' => 'Anmelden',
	'Mandator' => 'Mandant',
	'Mandator ID' => 'Mandanten ID',
	'Mandators' => 'Mandanten',
	//'Name' => 'Name',
	'New Position' => 'Neue Position',
	'Password Hash' => 'Passwort',
	'Password Reset Token' => 'Passwort zur Wiederherstellung',
	'Phone Business' => 'Telefon geschäftlich',
	'Phone Mobile' => 'Telefon Mobil',
	'Phone Privat' => 'Telefon privat',
	'Place' => 'Ort',
	'Please contact us if you think this is a server error. Thank you.' => '',
	'Please fill out the following fields to login:' => 'Bitte fülle die folgenden Felder aus, um dich anzumelden. :',
	'Please fill out the following fields to signup:' => 'Bitte fülle die folgenden Felder aus, um dich zu registrieren',
	'Please fill out your email. A link to reset password will be sent there.' => 'Bitte gib deine EMail ein. Ein Link zum zurücksetzen wird dahin gesendet.',
	'Pos Num' => 'Pos-Nr.',
	'Positions' => 'Positionen',
	'Prename' => 'Vorname',
	'Price' => 'Preis',
	'Print PDF' => 'PDF drucken',
	'Quantity' => 'Anzahl',
	'Request password reset' => 'Passwort zurücksetzen',
	'Remove' => 'Löschen',
	'Reset' => 'Zuzrücksetzen',
	'Reset password' => 'Passwort zurücksetzen',
	'Search' => 'Suche',
	'Select Customer' => 'Kunde auswählen',
	'Send' => 'Senden',
	'send' => 'senden',
	'Signup' => 'Registrieren',
	'State' => 'Bundesland',
	'Status' => 'Status',
	'Subject' => 'Betreff',
	'Submit' => 'Absenden',
	'Tax' => 'Steuer',
	'The above error occurred while the Web server was processing your request.' => '',
	'This is Reibach' => 'Dies ist Reibach',
	'This is the About page. You may modify the following file to customize its content:' => '',
	'This username has already been taken.' => 'Dieser Benutzername ist bereits vergeben.',
	'This email address has already been taken.' => 'Diese EMailAdresse ist bereits vergeben.',
	'Title' => 'Titel',
	'Unit' => 'Einheit',
	'Update' => 'Bearbeiten',
	'Update Time' => 'Bearbeitet am',
	'Update User ID' => 'Bearbeitet von',
	'Update Mandator: ' => 'Bearbeite Mandant:',
	'Update {modelClass}: ' => 'Bearbeite {modelClass}:',
	'Updated At' => 'Bearbeitet am',
	'User ID' => 'Benutzer ID',
	'Username' => 'Benutzername',
	'Users' => 'Benutzer',
	'Zipcode' => 'Postleitzahl',
	'amount' => 'Menge',
	'comment' => 'Kommentar',
	'email' => 'EMail',
	'fullName' => 'Name',
	'lastname' => 'Nachname',
	'login-button' => '',
	'name' => 'Name',
	'pos_num' => 'Pos-Nr.',
	'prename' => 'Vorname',
	'price' => 'Preis',
	'quantity' => 'Anzahl',
	'rememberMe' => 'Merke',
	'reset it' => 'setze es zurück.',
	'tax' => 'Steuer',
	'unit' => 'Einheit',
	'password' => 'Passwort',
	'username' => 'Benutzername',
	'User' => 'Benutzer',
	'Password' => 'Passwort',
);


$ergebnis = array_merge($array_leer, $array_voll);
//print_r($ergebnis);

foreach ($ergebnis as $key => $value) {
    // $arr[3] wird mit jedem Wert von $arr aktualisiert...
    echo "'{$key}' => '{$value}',\n";
}

?>
