<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => 'Sicher...?',
    'Article' => 'Artikel',
    'Articles' => 'Artikel',
    'Auth Key' => '',
    'Bills' => '',
    'Comment' => '',
    'Create' => '',
    'Create Article' => '',
    'Create Bill' => '',
    'Create Customer' => '',
    'Create Mandator' => '',
    'Create Position' => '',
    'Create User' => '',
    'Created At' => '',
    'Customer ID' => '',
    'Customers' => '',
    'Delete' => '',
    'Description' => '',
    'Email' => '',
    'Home' => '',
    'ID' => '',
    'Mandator ID' => '',
    'Mandators' => '',
    'Name' => '',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Positions' => '',
    'Price' => '',
    'Reset' => '',
    'Search' => '',
    'Status' => '',
    'Unit' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Updated At' => '',
    'User ID' => '',
    'Username' => '',
    'Users' => '',
];
